### ISSUE TITLE
BUG : Delete modal incorrect font

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#101]
**Description**
The text in the delete modal on the employee list screen is incorrect. It is currently Times New Roman whereas it should match the rest of the application. At the moment the font set for the entire application is Arial. 

**Acceptance Criteria**
The font for the text in the delete modal should match the rest of the application

**Comment by emab** [comment]
Is this to do with the modal opening up outside of `<div id="root">` and not getting the app style?

**Comment by emab** [comment]
After my last PR where I included the Roboto font ([as reccomended by Material UI](https://material-ui.com/getting-started/installation/)) this seems to be fixed. However it has caused some issues with layout from the previous font.

**Comment by emab** [comment]
@smangan360 think we can close this as it is now displaying the correct font in master?
