### ISSUE TITLE
BUG : Employee list capitalization

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#109]
**Description**
As a tidy up task, each word in the employee list should have it's first letter capitalized. This will allow for uniformity throughout the employee list component. See the screenshot below:

![image](https://user-images.githubusercontent.com/54022972/81715296-f91e1380-946f-11ea-81db-30515f90e704.png)

Once validation takes place, the list should now be in this state:
![image](https://user-images.githubusercontent.com/54022972/81715573-4a2e0780-9470-11ea-9c7f-9abc24bfd4d3.png)

**Acceptance Criteria**: 
- Each entry in the full/part time field should begin with a capital letter
- Each job title should begin with a capital letter
- Names will be taken as the user enters them

**Comment by QuarkNerd** [comment]
Do we not want to capitalize the 2nd word in name too?
