### ISSUE TITLE
BUG : H1 styling error

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#112]
**Description**
There is an issue with the styling of H1 headers on each screen of the application. Each header is 60px in size which is too large. Please see image below: 
![image](https://user-images.githubusercontent.com/54022972/81936107-95b7f100-95e9-11ea-8f72-eda9ea4d89bc.png)

**Acceptance Criteria**
- The headers should be a smaller 35px in size for each screen

**Comment by tjanowsk** [comment]
I think the 60px comes from the login screen's scss file, which carries over to other components.
instead of using `h1` we should probably define a header class and use it instead.

**Comment by QuarkNerd** [comment]
What is the issue? Has someone already fixed it

**Comment by tjanowsk** [comment]
> What is the issue? Has someone already fixed it

The h1 styling in the individual components says `2em`, but this is overwritten by `60px` from login screen's `h1`.
It's not been fixed yet.

**Comment by QuarkNerd** [comment]
> > What is the issue? Has someone already fixed it
> 
> The h1 styling in the individual components says `2em`, but this is overwritten by `60px` from login screen's `h1`.
> It's not been fixed yet.

Thanks and sorry, the description in the summary didnt load properly for some reason

**Comment by emab** [comment]
I've just looked into it and yeah it's due to me using `h1 { ... }` instead of a class, as only the class names  are scoped locally. Didn't realise this! Apologies 😊

**Comment by tjanowsk** [comment]
Closing because it's done
