### ISSUE TITLE
Bug DevTools failed to load SourceMap: Could not load content

### ISSUE THREAD

**Issue by QuarkNerd** [Furlough-Friends/rota-flex-101#116]
![image](https://user-images.githubusercontent.com/20900854/81949585-ea179c80-95fa-11ea-82ac-7b1a4e5d1d64.png)

**Comment by emab** [comment]
How do we recreate this? I can't see it in my console at the moment

**Comment by tjanowsk** [comment]
This looks like it's coming from a chrome extension, I certainly can't reproduce it.
If you want to pin in down maybe try disabling extensions one-by-one and see when the error disappears?

**Comment by QuarkNerd** [comment]
I believe its caused by adblock

**Comment by connorsettle** [comment]
Awaiting response from @QuarkNerd

**Comment by QuarkNerd** [comment]
> Awaiting response from @QuarkNerd 

Sorry,

It was indeed due to an extension
