### ISSUE TITLE
BUG : Multiple staff can be created from one email

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#121]
**Description**
At the moment, multiple users can be created using the email address. This will cause problems later down the line with authentication. There should a one to one relationship for a user and an email address.

**Acceptance Criteria**
- A user should not be able to be created if a user is already assigned to that email address 
- An appropriate error message should be sent back in the server response. 

**Note**
This was due to a requirement not being included in a ticket. No fault on a developer

**Comment by emab** [comment]
If the users email already exists in the database, what response do we want to send? Bad Request?

**Comment by emab** [comment]
Also shall we do this by using Hibernates `@Column(unique = true)`? It throws a `DataIntegrityViolationException` which can be caught in the Exception Handler and a better message can be sent to the front-end.
