### ISSUE TITLE
BUG : Header is the wrong colour and text should be changed

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#127]
When the sidebar was added to the project, a header was added. The header should be the same colour as the sidebar. Also, the page root is displayed in the header. This should be removed so the header only contains the buttons for opening/closing and the logout button. Please see the image below for the current state of the application: 
![image](https://user-images.githubusercontent.com/54022972/82216402-d5941680-9910-11ea-82f2-41607e5cb47c.png)

**Acceptance Criteria**
- The header should be the correct colour (#106cc8)
- The text should be removed from the header

The end result should match the image below: 
![image](https://user-images.githubusercontent.com/54022972/82216675-34599000-9911-11ea-8595-d7650db79c32.png)

**Comment by tjanowsk** [comment]
Fixed by a merged PR
