### ISSUE TITLE
BUG: Auth - User that isn't registered is able to access application

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#129]
**Description**
As a user that isn't registered to the application, I can access the application's front-end. I can't access any data which indicates the API's are protected. 

**Steps to Reproduce**
- Navigate to the login screen 
- Press the login button and sign in with your work email (which shouldn't be saved as a user in data.sql)
- Proceed through the steps of the login
- Accept Auth0 permissions 
**Issue**
Observe that you are able to access the employee screen even though you are not registered to the application. This should not be the case. 

**Acceptance Criteria**
- Given a user that is not registered the application, when they attempt to login they should be given a warning message stating that they are not registered to use the application and should be navigated back to the login screen.

**Comment by emab** [comment]
Yeah there's currently no check to the back-end. I thought potentially if someone logs in and their email isn't in the database they are navigated to a default page saying they need to request to be added via their manager?

**Comment by emab** [comment]
After chatting to Stephen we decided to try a temporary fix - after users log in a check will be made to see if they exist in the back-end. If they don't they will be redirected to a page saying they are not registered to use the application.

In the future, we will probably move to an invite only method. This means:

- When a manager adds a staff member, back-end will send a request to Auth0 to create a new user
- If successful, the user will also be added to database in back-end.
