### ISSUE TITLE
Rota screen : Add modal

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#137]
**Ticket in progess. There needs to be some discussion on the best way to do this**
As a manager, I want to be able to add employee shifts to the roster

**Comment by tjanowsk** [comment]
We need to decide how to trigger the add engagement modal.
Options include: add button, clicking on the rota, clicking and dragging on the rota screen, right-click context menu.

**Comment by emab** [comment]
I'd be leaning towards an add button plus some sort of context menu hybrid? Maybe the add button and left clicking open up a similar modal, but clicking opens at the clicked time whilst 'add' button just opens at current time/no time?
