### ISSUE TITLE
Add option to edit user

### ISSUE THREAD

**Issue by tjanowsk** [Furlough-Friends/rota-flex-101#143]
There are 2 main possibilities:
1. use a modal (basically re-purpose the 'add user' modal)
1. use ag-grid's edit functionality https://www.ag-grid.com/javascript-grid-cell-editing/

If we go with the latter option, we will have to restructure the table, which is currently NOT in one-to-one correspondence with the data.
For example 'name' column is squashed 'firstName' and 'surname', 'Part/full time' column is derived from 'workingHours' (with a loss of information) and some columns are missing altogrther (start date, salary etc.)

**Comment by connorsettle** [comment]
For me, editing in line in ag-grid is easiest and because this is manager view we are probably more interested in making it functional and clean rather than having a nice UI.

**Comment by connorsettle** [comment]
Alternatively might be nice to hook into create user modal with prefilled fields for consistency.

**Comment by tjanowsk** [comment]
Re-purposing add user model seems to be the easiest solution as it would not rely on us redesigning the entire table to match StaffDto structure.
