### ISSUE TITLE
CLEANUP - front end directory structure

### ISSUE THREAD

**Issue by tjanowsk** [Furlough-Friends/rota-flex-101#144]
Comment below to suggest a directory structure and comments what goes where, e.g.

src
|-models
| |- index.ts (typescript type definitions)
|- components
| |- sidebar (index.ts and scss styling file)

etc.

**Comment by connorsettle** [comment]
Things to address:
- [ ] Remove code that is not used serviceWorker.ts, json_server (we can recover from git history if we get a tester in future), etc.
- [ ] utils/string.ts => rename to capitalizeFirstLetter.ts
- [ ] Move common interfaces/types to src/model/...
- [ ] Where possible have constants that are used (or owned) by single component in the component file
- [ ] Naming convention for react appears to be PascalCase for components and lowerCamelCase for anything else - rename all files & folders accordingly. See https://github.com/airbnb/javascript/tree/master/react#naming
- [ ] Redux styleguide suggests feature folder or ducks but we are currently doing some mix of both: https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks. 

Question:
1. What do people think generally about default vs named exports? I think components default makes sense but perhaps other places (utils especially) named exports would make code more readable.
