### ISSUE TITLE
BUG - Employee table displays weirdly with a white box

### ISSUE THREAD

**Issue by emab** [Furlough-Friends/rota-flex-101#159]
![Screenshot 2020-06-04 at 18 49 44](https://user-images.githubusercontent.com/8884999/83793434-6f3f2000-a694-11ea-917d-730888943707.png)

Google chrome, master branch.

**Comment by tjanowsk** [comment]
This is related to ag-grid column width. The width of the last 2 columns is fixed, but the first 3 columns are automatic and not wide enough.

**Comment by connorsettle** [comment]
Use css to extend left panel width
