### ISSUE TITLE
Hourly rate not being set in database after adding new user

### ISSUE THREAD

**Issue by emab** [Furlough-Friends/rota-flex-101#181]
Tested on the deployed app so may be a problem with my database setup. Will test on local dev setup now.

UPDATE: Also doesn't work in local dev environment.

### Issue
When a user is added via the front-end, their hourly_rate column is 0.0 despite a number being entered.

**Comment by tjanowsk** [comment]
Works fine locally on the edit user PR

**Comment by emab** [comment]
Ah I didn't realise that pr hadn't gone in yet.
