### ISSUE TITLE
Move token authentication to axios interceptor

### ISSUE THREAD

**Issue by tjanowsk** [Furlough-Friends/rota-flex-101#185]
Currently we are using useAuth0 from the react wrapper, which can only be used inside  React components.

There are two ways around this:
- replace react auth0 with plain javascript one
- create a new React context that will pass get, set, put and post functions tochild components https://reactjs.org/docs/context.html

@emab @connorsettle  any thoughts?

**Comment by emab** [comment]
If we export a `getTokenSilently()` method from the auth0-spa component could we use that? I've seen an example where somebody seemed to do something like that:

```
export const getTokenSilently = async (...p) => {
  const client = await getAuth0Client()
  return await client.getTokenSilently(...p)
}
```

**Comment by emab** [comment]
This seems like how we can implement the interceptor using the current SDK setup:

https://github.com/auth0-samples/auth0-react-samples/issues/163#issuecomment-544764137

**Comment by tjanowsk** [comment]
> This seems like how we can implement the interceptor using the current SDK setup:
> 
> [auth0-samples/auth0-react-samples#163 (comment)](https://github.com/auth0-samples/auth0-react-samples/issues/163#issuecomment-544764137)

With this we have the same problem as the guy who replied below - the api is called inside a redux action and not a react component, so we can't use react hooks here.

Exporting getTokenSilently seems much more straightforward.

**Comment by emab** [comment]
> Exporting getTokenSilently seems much more straightforward.

Yeah agreed. If this does work then it could be a good option for now? The other option is, as you said, to switch to their plain JS implementation. We wouldn't have access to the hooks currently provided by the wrapper though.
