### ISSUE TITLE
BUG - Summary screen loads multiple times

### ISSUE THREAD

**Issue by tjanowsk** [Furlough-Friends/rota-flex-101#187]
~I think this is because we use separate dispatch for employees and engagements, we can replace them with a single dispatch that sets the store once.~
It's actually because the dispatch is called once before and once after the date picker component selects the dates.
We then need to decide what to display before the initial fetch is finalised

**Comment by emab** [comment]
We could make the summary page look like more of a dashboard, and the graph + pie chart look more like separate components. If the page layout was like this I think it would look fine to use the Material UI loaders to show in specific small areas of the screen whilst the data is fetched.
