### ISSUE TITLE
Create user endpoint

### ISSUE THREAD

**Issue by mangan360** [Furlough-Friends/rota-flex-101#30]
As a manager, when a new employee starts a job I want to be able to add them to the existing database. There should be an endpoint in place which takes user information as a payload and saves. A unique ID should be generated for this user and they should then saved in the database. 

Acceptance Criteria: 
- Given a user with admin (manager) access, when the manager makes a request to the createUser endpoint with the correct payload then a new user should be created in the database with a unique ID. The manager should receive an OK response.  
- Given a user with employee access, when the employee makes a request to the createUser endpoint, they should be get a bad response with a message stating that they don't have the correct access

**Comment by floyd924** [comment]
An employee trying to access this endpoint without Manager status shoudl receive 403 Forbidden
