### ISSUE TITLE
Get all shifts between dates endpoint

### ISSUE THREAD

**Issue by mangan360** [Furlough-Friends/rota-flex-101#37]
**Investigation needed on best way to do this. We may need two endpoints or one.**

As a manager I want to see the money being spent on wages for each job type of a period of a day, a week and a month. Each employee has an hourly rate attached to them, the endpoint should get all shifts worked. Breaks need to be deducted from each shift before displayed in the data. 

Acceptance Criteria: 
- Given when a manager queries the server for spending analysis for a single day then they should get back the spending analysis for each job sector (front of house, back of house, manager, ...). 
- Given when a manager queries the server for spending analysis for a week then they should get back spending analysis for each job sector (front of house, back of house, manager, ...). 
- Given when a manager queries the server for spending analysis for a month then they should get back the spending analysis for each job sector (front of house, back of house, manager, ...). 

**Notes**
- Breaks need to be deducted from the shifts
- Unpaid holidays should not be included
- Paid holidays should be included

**Comment by emab** [comment]
> money being spent on wages for each job type

Currently job type is just a string which is typed by the manager, so we are relying on no spelling mistakes / consistency in their approach to naming job titles i.e chef != Chef != Cook != Kitchen. Is it outside MVP to ensure this data is consistent?
