### ISSUE TITLE
Authentication setup

### ISSUE THREAD

**Issue by mangan360** [Furlough-Friends/rota-flex-101#41]
As a PO, I want infrastructure in place so users can sign into the application through an authorization system. Only **active users** will be able to login.

Acceptance Criteria: 
-   Given when a user is an employee of the company, when they attempt to login to the application then they are brought to the landing page of the app. 
- Given when a user who isn't an employee of the company, when they attempt to login to the application then they are prompted with a message "You don't have access to this application"

**Comment by duncstin** [comment]
There are a number of elements involved with this task, allowing it to be broken down into a series of logical steps. Writing this with the assumption we're using Auth0, but if we choose a different service the same approach should be adopted: [Authorization Code Flow with Proof Key for Code Exchange](https://auth0.com/docs/flows/concepts/auth-code-pkce). (Worth noting: some guides may suggest using the [Implicit Flow](https://auth0.com/docs/flows/concepts/implicit), but this is only appropriate for logging in, and is not longer considered best practice to obtain access tokens).

A rough breakdown of tasks involved is as follows.

- Signup for Auth0, and [configure it appropriately](https://auth0.com/docs/architecture-scenarios/spa-api/part-2). This involves:
  - signing up to Auth0,
  - Adding the API, and configuring scopes,
  - Adding the frontend (SPA) and configuring permissions
  - (Optionally, create 2 dummy users, an Admin and a normal employee)
You may need to read up on Auth0's [scopes](https://auth0.com/docs/scopes/current/api-scopes#example-an-api-called-by-a-first-party-application) and [roles](https://auth0.com/docs/authorization/concepts/rbac).
Also note that setup for front and back end is shown a bit in links below.

- Authenticate the user on the front end. This boils down to obtaining an **Access Token** for the current user, which will be needed to access our API. This task is simplified by the existence of [Auth0's SPA SDK](https://auth0.com/docs/libraries/auth0-spa-js). For example usage with react, see the [quickstart](https://auth0.com/docs/quickstart/spa/react), which introduces some custom hooks. 

- Secure the backend. The backend should check for a valid access token for all endpoints. Additionally, it should ensure only an Admin can access admin specific endpoints. See the [example using Spring](https://auth0.com/docs/quickstart/backend/java-spring-security5). Note that when [validating the access token](https://auth0.com/docs/tokens/guides/validate-access-tokens).

- Investigate (and implement) programmatic creation of new users. Until this point we have likely been using dummy users to check the correct distinction between admin and non-admin, and it is likely these have been created through the Auth0 dashboard. Naturally, we will want admins to be able to add new users through our own app. Creating a new user will involve adding them to our own database, and to Auth0, which can be done using their [management API](https://auth0.com/docs/users/guides/manage-users-using-the-management-api). See alsp: [invite only applications](https://auth0.com/docs/design/creating-invite-only-applications), as we'll only want staff to be registered with the app.

To consider for the front end: (probably merits further discussion), handling token time outs, automatic refresh of tokens

**Comment by QuarkNerd** [comment]
Do we want to use RS256 or HS256? the difference seems to be whether they use a public/private key pair or just a private key.

Also For the 'identifier' it wants a URL that can't be changed. I cant seem to see what it is for?

**Comment by duncstin** [comment]
Is there a suggested default for symmetric vs asymmetric? I guess I'd be inclined to go with public/private key pair, but I'm not sure I know enough to make a decision without looking into it for a bit longer.

as for the second part:

> Identifier: a unique identifier for the API. We recommend using a URL but note that this doesn't have to be a publicly available URL, Auth0 will not call your API at all. This value cannot be modified afterwards.

[Source](https://auth0.com/docs/architecture-scenarios/spa-api/part-2)

I would just go with something sensible, given that we haven't deployed anything and are unlikely to buy a domain name.

**Comment by QuarkNerd** [comment]
all I can see is that RS256 is easier because many frameworks can automatically fetch the public key. Im not sure if it is actually more secure

**Comment by duncstin** [comment]
Let's stick with the easier option for now I guess?

**Comment by QuarkNerd** [comment]
Okay, sensible non-URL name and RS256

**Comment by QuarkNerd** [comment]
I've started creating this app. The docs seem to be slightly out of date btw, unless Ive messed up. However I think we need slightly more information on the exact structure before I add more stuff. For now ive added some of you guys to the account so feel free to check it out. Msg me if you need to be added and havent yet

**Comment by emab** [comment]
>  Only active users will be able to login.
How do we define an active user? Does a manager need to log in, set up a company and then invite people to join?

**Comment by JAStrachan** [comment]
Good question - I think they probably would have to invite people in!

**Comment by emab** [comment]
Okay well at the moment, [this PR](https://github.com/Furlough-Friends/rota-flex-101/pull/65) adds a basic login button which is linked to Auth0. 

A user can now log in and information about the user session can be used via the Auth0 hooks. [these docs](https://auth0.github.io/auth0-spa-js/index.html) will be useful for anyone working on the front-end that needs access to the users tokens/information.
