### ISSUE TITLE
Create 'Add' user modal

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#59]
**Requires #58**
When the user clicks the add button, a modal should appear with a form with input values with the required fields : 
- First Name 
- Surname
- Job title
- Contracted hours
- Pay
- Preferred days (radio button)

Should have three buttons: 
- Add - button should have same styling as initial 'Add' button at the base of the modal
- Cancel - button should be coloured slightly differently to distinguish a difference between functionality at the base of the modal beside the 'Add' button
- x - An close option in the top right of the modal 
**When the initial 'Add' button is clicked, the modal appears and there is a dark semi transparent overlay behind the modal allowing for more focus on the modal.**

Each input box should have two states: 
- Inactive - grey outline
- Active - when a manager is interacting with an input box the outline should change to a blue colour: 
![image](https://user-images.githubusercontent.com/54022972/79996005-d8395280-84af-11ea-9c0d-c154accc02e1.png)

**Comment by emab** [comment]
Material UIs text inputs look a lot like how you want:

![image](https://user-images.githubusercontent.com/8884999/80085599-56e5cc80-8550-11ea-9de6-8b240c24b2e3.png)

And it's got cool built in things like this:

![image](https://user-images.githubusercontent.com/8884999/80085661-7250d780-8550-11ea-9eb8-a00a24b0e95c.png)


https://codesandbox.io/s/material-demo-m0tmb

**Comment by QuarkNerd** [comment]
is pay hourly/weekly/monthly or do we give a choice?

**Comment by QuarkNerd** [comment]
Do we want to add start date and ROLE?

**Comment by smangan360** [comment]
#121 outlines that there can't be more than one users linked to an email address. It will probably have implications on the add modal for error handling. I'll add another ticket in now
