### ISSUE TITLE
Roster screen: create basic view without data

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#87]
This should be a D3 chart. The inspiration behind this is Google Calendar. 
Y-axis - time
X-axis - days

Using D3 so we can eventually add clickable boxes for time entries.  

The time should be in a 24 hour clock and have the full week, 7 days, displayed.

**Comment by JAStrachan** [comment]
Its a graph that shows the hours down one side. It should render this all as light square boxes. We are basically copying google calendar!

**Comment by JAStrachan** [comment]
The reason we are using D3 is that we need the flexibility it provides. A shift can start at any time so we can't create a table for that.

**Comment by JAStrachan** [comment]
![image](https://user-images.githubusercontent.com/23055587/81068000-87762080-8ed7-11ea-92d5-5864ebaa3646.png)
This needs the weekends on it as well! But thats some basic sketches

**Comment by tjanowsk** [comment]
This looks like a calendar component. Do we need d3? It seems that e.g. fullcalendar.io can do this out-of-the-box.
