### ISSUE TITLE
Summary Screen: Create hourly breakdown chart

### ISSUE THREAD

**Issue by smangan360** [Furlough-Friends/rota-flex-101#93]
As a manager, I want to be able to see a total breakdown of employee working hours. This will allow for better understanding on expenses while giving a general breakdown of staff. The information should be represented in a pie chart. The total number of hours (including holidays) in that period should in the center of the pie chart and each time type should be allocated a colour. 

**Acceptance Criteria**
- There should be a pie chart on the top left of the summary page taking up about half the width of the page (see mock designs for an idea)
- There should be a header of the chart saying 'Hourly Breakdown'
- The chart should display the breakdown of hours for that selected period. (Including holidays)
- The chart should have the total numbers of hours worked in the center (similar to Kimble holiday pie chart) 
- Each job type should be given a specific colour. The colour breakdown will be displayed in the colour breakdown component. For testing purposes, include some text on each segment of the chart to show which job it represents. This can be removed later
- Sign into Kimble and observe how the pie chart loads. If possible it would be great to include a similar animation on load for our summary screen if possible. This is not a major requirement to include but it would be great to include. 

**Please see image below for styling**
![image](https://user-images.githubusercontent.com/54022972/81182325-8dd2ce00-8fa5-11ea-94ef-a40dc2632307.png)

**Notes**
- Tool tip is out of scope of this task

**Comment by tjanowsk** [comment]
What are the job types? I think currently we only store engagementType which is either work or holiday.
